### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by pvulakh** [cireuj12/forthegram#1]
Good job on your schema! Some changes to make: 
### `users` table: 
- [x] Remove `profile_picture_url` column here - AWS will supply photos for us, so we don't need to store these in our database. 
### `photos` table: 
- [x] Remove the `photo_url` column here as well 
- [x] Consider renaming the `photos` table to a `posts` table to avoid having code like `photo.photo` later on :)
- [x] Add a column of type `text` for your `photos` table so that users can have an optional caption on their photos.
### `comments` table: 
Don't worry about making these look like they're nesting! 
- [x] Add a column of type `text` for your `comments` table so that we store the body of the comment.
- [x] Remove the unique index on `[ :user_id, :photo_id]` since we want a `user` to be able to create multiple comments on one `photo`, and let's add separate indices for `user_id` and `photo_id`.
### `likes` table: 
As you noted at the end of your schema, users can like `comments` and `photos`. This means we're dealing with polymorphic associations. 
- [x] Let's add a `likeable_type` column to the `likes` table and change the `foreign_key` of `photo_id` to now be `likeable_id`
- [x] Modify the composite index to now be on `[ :user_id, :likeable_type, :likeable_id ]` so that a `user` can like a `comment` with an `id` of 1 as well as a `photo` with an id of 1. Let me know if you have any questions on this!
### miscellaneous: 
- [x] Stories sound really cool to implement, but let's label that as a bonus feature for later
- [x] Add a `follows` join table so you keep track of a `user`'s followers as well as who they follow. 
- [x] Add all your associations to your tables!

Let me know if you have questions on any of this!

**Comment by cireuj12** [comment]
5/28/2019:

- Should the composite index of [ :user_id, :likeable_type, :likeable_id ] be unique?
- By adding assocations in the table, do you want those to labeled out in the schema as well?
