### ISSUE TITLE
MVPs

### ISSUE THREAD

**Issue by pvulakh** [cireuj12/forthegram#2]
Great work on this! A few things to change: 

- [x] Move the Following MVP (currently #3) to after you've built out user profiles since users follow other users by first going on their profiles. 
- [x] Consider having User Profiles be its own MVP, and lumping Following and Dashboard into a separate one. Let me know if you want to discuss this! 
- [x] Search should be a bonus feature :) 

Let me know if you have any questions. Again, really good job on this!

**Comment by cireuj12** [comment]
Issues addressed!
